doctrine:
  dbal:
    override_url: true
    url: "%env(resolve:DATABASE_URL)%"
    schema_filter: ~^(?!sessions)~
    types:
      safe_date: DobryProgramator\DoctrineSafeTypes\Type\SafeDateType
      safe_date_immutable: DobryProgramator\DoctrineSafeTypes\Type\SafeDateImmutableType
      safe_datetime: DobryProgramator\DoctrineSafeTypes\Type\SafeDateTimeType
      safe_datetime_immutable: DobryProgramator\DoctrineSafeTypes\Type\SafeDateTimeImmutableType
      safe_datetimetz: DobryProgramator\DoctrineSafeTypes\Type\SafeDateTimeTzType
      safe_datetimetz_immutable: DobryProgramator\DoctrineSafeTypes\Type\SafeDateTimeTzImmutableType
      safe_time: DobryProgramator\DoctrineSafeTypes\Type\SafeTimeType
      safe_time_immutable: DobryProgramator\DoctrineSafeTypes\Type\SafeTimeImmutableType
    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
