version: '3'

services:

    database:
        build:
            context: ./database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        restart: always
        ports:
            - ${DATABASE_PORT}:3306
        volumes:
            - ../database:/var/lib/mysql
        env_file:
            - .env

    php:
        container_name: "phpfpm"
        build:
            context: ./php
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.9
        volumes:
            - ${APP_FOLDER}:/var/www

    nginx:
        build:
            context: ./nginx
        volumes:
            - ${APP_FOLDER}:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../logs/nginx:/var/log/nginx
        depends_on:
            - php
        ports:
            - ${NGINX_LOCAL_PORT}:80
